### ISSUE TITLE
HtmGem does not need mysql and is AGPLv3

### ISSUE THREAD

**Issue by Sbgodin** [YunoHost-Apps/my_capsule_ynh#7]
### Describe the bug

According to the documentation, HtmGem uses mysql. As far as I know, it's not the case. It only needs a web server (Nginx and Apache are supported) and Php.
The manifest says it's GPLv3. Indeed, it's [AGPLv3](https://gmi.sbgodin.fr/htmgem/COPYING.gmi).

Thanks for all the work of integration :+1:

**Comment by yalh76** [comment]
Hi,

Just changed the licence to AGPLv3

As my_capsule_ynh is based on gemserv and as gemserv manage cgi, I though that already having a mysql database could be usefull for cgi

**Comment by Sbgodin** [comment]
Nice :-) Thanks for the update!
